# Generated by Django 5.2 on 2025-04-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataString0', models.URLField()),
                ('dataString1', models.DateTimeField()),
                ('dataString2', models.CharField(blank=True, max_length=100, null=True)),
                ('dataString3', models.CharField(max_length=20)),
                ('dataString4', models.CharField(blank=True, max_length=40, null=True)),
                ('dataString5', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('dataString6', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
