# Generated by Django 5.2 on 2025-04-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='dataString5',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=40, null=True),
        ),
    ]
