# Generated by Django 5.2 on 2025-04-05 19:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0002_alter_dataentry_datastring5'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncBag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='SyncData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(-1, 'Discarded'), (0, 'Current'), (1, 'Read-only')])),
                ('created', models.DateTimeField()),
                ('dataString0', models.URLField()),
                ('dataString1', models.DateTimeField()),
                ('dataString2', models.CharField(blank=True, max_length=100, null=True)),
                ('dataString3', models.CharField(max_length=20)),
                ('dataString4', models.CharField(blank=True, max_length=40, null=True)),
                ('dataString5', models.DecimalField(blank=True, decimal_places=0, max_digits=40, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SyncItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1)),
                ('sync_bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_items', to='dataprocessor.syncbag')),
            ],
        ),
        migrations.DeleteModel(
            name='DataEntry',
        ),
        migrations.AddField(
            model_name='syncdata',
            name='sync_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='dataprocessor.syncitem'),
        ),
    ]
