# Generated by Django 5.2 on 2025-04-05 19:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0003_syncbag_syncdata_syncitem_delete_dataentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappedSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('account', models.UUIDField()),
            ],
        ),
        migrations.AddField(
            model_name='syncdata',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='syncdata',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='syncdata',
            name='sync_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_versions', to='dataprocessor.syncitem'),
        ),
        migrations.AlterField(
            model_name='syncitem',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
    ]
