# Generated by Django 5.2 on 2025-04-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0004_mappedsource_syncdata_is_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('dataString0', models.URLField()),
                ('dataString1', models.DateTimeField()),
                ('dataString2', models.CharField(blank=True, max_length=100, null=True)),
                ('dataString3', models.CharField(max_length=20)),
                ('dataString4', models.CharField(blank=True, max_length=40, null=True)),
                ('dataString5', models.DecimalField(blank=True, decimal_places=0, max_digits=40, null=True)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='MappedSource',
        ),
        migrations.RemoveField(
            model_name='syncitem',
            name='sync_bag',
        ),
        migrations.RemoveField(
            model_name='syncdata',
            name='sync_item',
        ),
        migrations.DeleteModel(
            name='SyncBag',
        ),
        migrations.DeleteModel(
            name='SyncData',
        ),
        migrations.DeleteModel(
            name='SyncItem',
        ),
    ]
