# Generated by Django 5.2 on 2025-04-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0005_dataentry_delete_mappedsource_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataentry',
            options={'ordering': ['-dataString1'], 'verbose_name': 'Data Entry', 'verbose_name_plural': 'Data Entries'},
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='dataString0',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='dataString1',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='dataString2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='dataString3',
            field=models.CharField(max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='dataString4',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Optional Field'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='dataString5',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=40, null=True, verbose_name='Numeric Value'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='grade',
            field=models.IntegerField(help_text='Quality grade (0=F, 4=A)'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='unique_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Unique Identifier'),
        ),
    ]
